### ISSUE TITLE
Wikitten Deploy

### ISSUE THREAD

**Issue by nicklinyi** [zohead/wikitten-and-mdwiki#1]
Wikitten 本地可以浏览， 但原作者似乎没提及 Deploy 到网站， 比如如何deploy 到 gh-pages。 求教

**Comment by zohead** [comment]
MDwiki 可以本地浏览，Wikitten 基于 PHP 的不行吧，自然也不能部署到 gh-pages 了。
MDwiki 部署到 gh-pages 很简单哦，我也部署过一个到 coding 上。

**Comment by nicklinyi** [comment]
soga。谢谢了
